package forgeofovorldule.anvilory

var ts_New_plot = "New plot"
var ts_This_is_an_example_story = "This is an example story"
var ts_New_chapter = "New chapter"
var ts_loading = "loading"
var ts_app_icon = "app icon"
var ts_Your_plots = "Your plots"
var ts_story = "story"
var ts_movie = "movie"
var ts_days_ago = "days ago"
var ts_Description = "Description"
var ts_Create_a_plot = "Create a plot"
var ts_To_change_an_item__click_ = "To change an item, click on it"
var ts_Create = "Create"
var ts_Cancel = "Cancel"

fun changeLanguage() {
    if (languages == Languages.RU) {
        ts_New_plot = "Новый сюжет"
        ts_This_is_an_example_story = "Это пример истории"
        ts_New_chapter = "Новая глава"
        ts_loading = "загрузка"
        ts_app_icon = "иконка приложения"
        ts_Your_plots = "Ваши сюжеты"
        ts_story = "история"
        ts_movie = "фильм"
        ts_days_ago = "дней назад"
        ts_Description = "Описание"
        ts_Create_a_plot = "Создать сюжет"
        ts_To_change_an_item__click_ = "Чтобы изменить элемент, нажмите на него"
        ts_Create = "Создать"
        ts_Cancel = "Отмена"
    } else {
        ts_New_plot = "New plot"
        ts_This_is_an_example_story = "This is an example story"
        ts_New_chapter = "New chapter"
        ts_loading = "loading"
        ts_app_icon = "app icon"
        ts_Your_plots = "Your plots"
        ts_story = "story"
        ts_movie = "movie"
        ts_days_ago = "days ago"
        ts_Description = "Description"
        ts_Create_a_plot = "Create a plot"
        ts_To_change_an_item__click_ = "To change an item, click on it"
        ts_Create = "Create"
        ts_Cancel = "Cancel"
    }
}